version: '3.8'
services:
  backend:
    image: ${BACKEND_IMAGE}:${APP_VERSION}
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  frontend:
    image: ${FRONTEND_IMAGE}:${APP_VERSION}
    ports:
      - "80:80"
    restart: unless-stopped